### ISSUE TITLE
rails 5.1 support for change_column

### ISSUE THREAD

**Issue by fruwe** [iangreenleaf/native_enum#11]
I am currently using rails 5.1.2, ruby 2.4.1

I tried to run the following migration:

```
class AddUsersOneTimeStatus < ActiveRecord::Migration[5.1]
  def change
    change_column :users, :status, :enum, limit: %w(active one_time inactive), default: 'active', null: false
  end
end
```

which caused the following error:

```
Mysql2::Error: Invalid default value for 'status': ALTER TABLE `users` CHANGE `status` `status` enum('[:limit, ["active", "one_time", "inactive"]]','[:default, "active"]','[:null, false]','[:comment, nil]','[:primary_key, false]') DEFAULT 'active' NOT NULL
/no/need/to/know/db/migrate/20170626163720_add_users_one_time_status.rb:3:in `change'
ActiveRecord::StatementInvalid: Mysql2::Error: Invalid default value for 'status': ALTER TABLE `users` CHANGE `status` `status` enum('[:limit, ["active", "one_time", "inactive"]]','[:default, "active"]','[:null, false]','[:comment, nil]','[:primary_key, false]') DEFAULT 'active' NOT NULL
```

This problem occurs because the parameters of `ActiveRecord::ConnectionAdapters#type_to_sql` changed from `type, limit=nil, *args` to `(type, limit: nil, precision: nil, scale: nil, unsigned: nil, **)`
. This is caused by the following change in activerecord 5.1:

https://github.com/rails/rails/commit/ae39b1a03d0a859be9d5342592c8936f89fcbacf#diff-98ce5dc0cd01f8b0435ff6feac10d8a8

monkey patch (please this e.g. inside config/initializers/):

```
# monkey patch for native_enum-1.0.0
# fixes change_column bug - https://github.com/iangreenleaf/native_enum/issues/11

require 'native_enum'
require 'connection_adapters/mysql2'

module ActiveRecord
  module ConnectionAdapters
    existing_class = defined?( Mysql2Adapter ) ? Mysql2Adapter : AbstractMysqlAdapter

    existing_class.class_eval do
      # def type_to_sql_with_enum type, limit=nil, *args
      def type_to_sql_with_enum_fix(type, limit: nil, **options)
        if type.to_s == "enum" || type.to_s == "set"
          "#{type}(#{quoted_comma_list limit})"
        else
          type_to_sql_without_enum type, limit: limit, **options
        end
      end
      alias_method :type_to_sql, :type_to_sql_with_enum_fix
    end
  end
end
```

**Comment by iangreenleaf** [comment]
Thanks so much for the detailed report! I'm having a busy month and it will likely be a couple weeks before I can look at this. But you're not being ignored!

**Comment by mcls** [comment]
Hi @iangreenleaf, I decided to take a stab at this. You can find the related PR's here: https://github.com/iangreenleaf/native_enum/pull/12 + https://github.com/iangreenleaf/native_enum/pull/13

**Comment by peterwake** [comment]
@mcls @iangreenleaf  just FYI I tried using this branch, and was getting `ActiveRecord Validation failed` errors on my models (which I don't get using the original). This is occuring where I had

```ruby
belongs_to :communication
```

Which I could solve by adding 

```ruby
belongs_to :communication, optional: true
```

However for models where I had 

```ruby
class Communication < ApplicationRecord

  has_many :communications_stores

  has_many :stores, -> { distinct },
    through: :communications_stores
```

And I do

```
Communication.create(stores: stores)
```

It blew up. I couldn't work out how to stop it throwing the error in this case.
